# Generated by Django 4.2.13 on 2024-07-04 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('price', models.JSONField()),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('color', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=50)),
                ('fabric', models.CharField(max_length=50)),
                ('disclaimer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecommerce_app.product')),
            ],
        ),
    ]
